pipeline {
    //agent any

    agent { node { label 'AGENT-1' } }
    options {
        ansiColor( 'xterm' )
    }

    stages {
        stage('Init') {
            steps {
                sh '''
                   cd 01-vpc
                   ls -ltr
                   pwd                
                   terraform init
                '''
            }
        }
        stage('Plan') {
            steps {
                sh '''
                   cd 01-vpc
                   ls -ltr
                   pwd                
                   terraform plan
                '''
            }
        }
        stage('Approve') {
            steps {
                input 'Shall I Apply?'
            }
        }
        stage('Apply') {
            steps {
                sh '''
                  pwd
                  ls -ltr
                  cd 01-vpc/
                  terraform apply -auto-approve
                '''
            }
        }
    }   

    post {
        always {
            echo 'I will always run whether job is success or not'
        }
        success {
            echo 'I will run only when the job is success'
        }
        failure {
            echo 'I will run when the job is failure'
        }
    }
}